### PR TITLE
[V0.1] Initial refactoring of GUI to conform to V0.1 specifications

### PR DESCRIPTION
**Pull request by Skaty**
Resolves issue #5 (#4 resolution, as it is a prerequisite).

### CODE REVIEW

**Comment by Skaty** [comment]
@advaypal @AHaliq @SukiTsang. Please check and approve.

**Comment by advaypal** [comment]
@Skaty Your commits look ok to me, can someone review mine?

**Comment by advaypal** [comment]
JUnit tests are failing

**Comment by advaypal** [comment]
Ok it works

**Review by advaypal — APPROVED** [review]
+1

**Pull request merged**
