### PR TITLE
Remove recurring tasks support

### PR DESCRIPTION
**Pull request by Skaty**

### CODE REVIEW

**Review by SukiTsang — APPROVED** [review]

**Comment by SukiTsang** [comment]
wait for @advaypal

**Review by advaypal — CHANGES_REQUESTED** [review]
Are you sure we can just leave it in the codebase like that? I think we need to remove the code completely

**Comment by SukiTsang** [comment]
In the handbook, it mentions unused code can still put in the code base if we state the reason.
I think should be fine?

**Review by advaypal — APPROVED** [review]

**Comment by advaypal** [comment]
As long it's ok to have unused code.

**Comment by Skaty** [comment]
Test works on PC. Travis is taking 30 minutes.

**Pull request merged**
