### PR TITLE
Update Logic class diagram

### PR DESCRIPTION
**Pull request by Skaty**

### CODE REVIEW

**Comment by SukiTsang** [comment]
@Skaty You also need to add the find tag command and parser in the diagram

**Comment by Skaty** [comment]
@SukiTsang need to see if we can merge that first.

**Comment by SukiTsang** [comment]
ok

**Review by SukiTsang — APPROVED** [review]

**Review by advaypal — APPROVED** [review]

**Comment by Skaty** [comment]
Travis does not need to pass, since it's just documentation changes.

**Pull request merged**
